### ISSUE TITLE
Wand Charges broken since 5.11.0

### ISSUE THREAD

**Issue by Pyroman2xxx** [foundryvtt/pf2e#12284]
Wands charges do not change when using it. Also, the number of charges remaining cannot be altered; it is immediately reset to 1.

Console error when it occurs:

> foundry.js:752 Uncaught (in promise) TypeError: Cannot set property message of  which has only a getter
>     at Hooks.onError (foundry.js:752:30)
>     at foundry.js:5771:13
> onError @ foundry.js:752
> (anonymous) @ foundry.js:5771
> Promise.catch (async)
> render @ foundry.js:5769
> render @ foundry.js:7111
> render @ foundry.js:14259
> _onUpdateDescendantDocuments @ foundry.js:14485
> _onUpdateDescendantDocuments @ foundry.js:19170
> _dispatchDescendantDocumentEvents @ foundry.js:14405
> #handleUpdateDocuments @ foundry.js:13715
> await in #handleUpdateDocuments (async)
> _updateDocuments @ foundry.js:13458
> await in _updateDocuments (async)
> update @ commons.js:8677
> await in update (async)
> updateDocuments @ commons.js:8001
> update @ commons.js:8098
> consume @ pf2e.mjs:1644
> (anonymous) @ pf2e.mjs:1350

**Comment by Pyroman2xxx** [comment]
I loaded 5.11.3 and tested but the issue remains exactly the same. Using the wand does not consume a charge and you cannot manually edit the remaining charges. The console error is no longer there though.
Would it be better if I opened a new issue on this?
