### ISSUE TITLE
Attempting to refresh items on compendium actors results in error

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#16512]
For example, I tried refreshing "Ezren (Level 1)"'s "Staff", "Hand of the Apprentice", and "Cooperative Nature":

```
pf2e.mjs:1 Uncaught (in promise) Error: PF2e System | Item "Staff" (Compendium.pf2e.iconics.Actor.WNX5OQKPh4uaV7mW.Item.epNtNWhBdtOOmHYs) is its own source.
    at ErrorPF2e (pf2e.mjs:1:8618)
    at WeaponPF2e.refreshFromCompendium (pf2e.mjs:1580:215786)
    at Object.onclick (pf2e.mjs:1607:56784)
    at HTMLAnchorElement.<anonymous> (foundry.js:5982:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
ErrorPF2e @ pf2e.mjs:1
refreshFromCompendium @ pf2e.mjs:1580
```

```
pf2e.mjs:1 Uncaught (in promise) Error: PF2e System | Item "Hand of the Apprentice" (Compendium.pf2e.iconics.Actor.WNX5OQKPh4uaV7mW.Item.pnIzRwwzr80qTOcw) is its own source.
    at ErrorPF2e (pf2e.mjs:1:8618)
    at SpellPF2e.refreshFromCompendium (pf2e.mjs:1580:215786)
    at Object.onclick (pf2e.mjs:1607:56784)
    at HTMLAnchorElement.<anonymous> (foundry.js:5982:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
ErrorPF2e @ pf2e.mjs:1
refreshFromCompendium @ pf2e.mjs:1580
```

```
pf2e.mjs:1 Uncaught (in promise) Error: PF2e System | Item "Cooperative Nature" (Compendium.pf2e.iconics.Actor.WNX5OQKPh4uaV7mW.Item.tU36WCoQKCSx7dgW) is its own source.
    at ErrorPF2e (pf2e.mjs:1:8618)
    at FeatPF2e.refreshFromCompendium (pf2e.mjs:1580:215786)
    at Object.onclick (pf2e.mjs:1607:56784)
    at HTMLAnchorElement.<anonymous> (foundry.js:5982:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
ErrorPF2e @ pf2e.mjs:1
refreshFromCompendium @ pf2e.mjs:1580
```

**Comment by stwlam** [comment]
Are they in fact their own sources? That error is only thrown when the item's UUID is identical to its source ID.

**Comment by simonward** [comment]
Sorry, missed your question.

No, Ezren's Hand of the Apprentice is:
```
"_id": "pnIzRwwzr80qTOcw",
"flags": {
	"core": {
		"sourceId": "Compendium.pf2e.spells-srd.Item.bSDTWUIvgXkBaEv8"
	}
}
```

Attempting to refresh it emits:
`pf2e.mjs:1 Uncaught (in promise) Error: PF2e System | Item "Hand of the Apprentice" (Compendium.pf2e.iconics.Actor.WNX5OQKPh4uaV7mW.Item.pnIzRwwzr80qTOcw) is its own source.
`

**Comment by simonward** [comment]
It's important to note that it must be a Compendium actor. Imported actors work fine.

**Comment by simonward** [comment]
@ammalagonc and @pedrogrullada were able to reproduce the issue.

**Comment by CarlosFdez** [comment]
Repro'd. The thing to stress is that its a compendium actor. The reason is that item.sourceId is always the uuid if its a compendium even if its embedded.
