### ISSUE TITLE
issue ver. 3.12.0.8 unable to open character sheet with other issues

### ISSUE THREAD

**Issue by thesnaglebeast** [foundryvtt/pf2e#2775]
Hi just upgraded to 3.12.0.8 but when I log in I get these errors
`
foundry.js:4656 Uncaught (in promise) Error: ENOENT: no such file or directory, open '/foundry/data/Data/systems/pf2e/templates/items/background-sidebar.html'
[Detected 1 package: system:pf2e]
    at o.<anonymous> (foundry.js:4656:40)
    at o.value (socket.js:307:17)
    at o.value (socket.js:237:22)
    at T.emit (index.js:143:20)
    at s.value (manager.js:200:14)
    at T.emit (index.js:143:20)
    at a.value (index.js:105:51)
    at s.value (manager.js:192:22)
    at T.emit (index.js:143:20)
    at a.value (socket.js:323:26)
    at T.emit (index.js:143:20)
    at o.value (transport.js:99:14)
    at o.value (transport.js:92:14)
    at ws.onmessage (websocket.js:76:40)
`

`
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'value')
[Detected 1 package: system:pf2e]
    at CharacterPF2e.setNumericRollOptions (main.bundle.js:1:80651)
    at CharacterPF2e.prepareEmbeddedDocuments (main.bundle.js:1:69356)
    at CharacterPF2e.prepareData (foundry.js:10771:10)
    at CharacterPF2e.prepareData (main.bundle.js:1:24531)
    at CharacterPF2e.prepareData (main.bundle.js:1:65853)
    at CharacterPF2e._initialize (foundry.js:10568:12)
    at CharacterPF2e._initialize (main.bundle.js:1:24407)
    at new Document (document.mjs:52:10)
    at new BaseActor (documents.mjs:62:1)
    at new <anonymous> (foundry.js:10541:5)
    at new Actor (foundry.js:13402:5)
    at new ActorPF2e (main.bundle.js:1:20918)
    at new CreaturePF2e (main.bundle.js:1:156129)
    at new CharacterPF2e (main.bundle.js:1:61716)
    at new ActorPF2e (main.bundle.js:1:20637)
    at ActorsPF2e._initialize (foundry.js:11458:15)
    at new WorldCollection (foundry.js:11444:10)
    at new Actors (foundry.js:11650:1)
    at new ActorsPF2e (main.bundle.js:1:514344)
    at Game.initializeDocuments (foundry.js:5585:30)
    at Game.setupGame (foundry.js:5533:10)
    at async Game._initializeGameView (foundry.js:6514:5)
`

When I try to open the character sheet I get this error

`
d {description: undefined, fileName: undefined, lineNumber: undefined, endLineNumber: undefined, message: 'The partial systems/pf2e/templates/actors/partials…ld not be found\n[Detected 1 package: system:pf2e]', …}
description: undefined
endLineNumber: undefined
fileName: undefined
libwrapper_skip_package_detection: true
lineNumber: undefined
message: "The partial systems/pf2e/templates/actors/partials/dying-pips.html could not be found\n[Detected 1 package: system:pf2e]"
name: "Error"
number: undefined
stack: "Error: The partial systems/pf2e/templates/actors/partials/dying
`

happens in new and old worlds, running the trouble shooter doesn't fix it, nor does restarting foundry.

**Comment by stwlam** [comment]
This can happen if Foundry fails to properly download and upgrade a system. Try uninstalling the pf2e system, ensuring the Data/systems/pf2e folder is really gone, and finally reinstalling the system.

**Comment by thesnaglebeast** [comment]
tried it but unfortunately, it didn't change anything.

is there anywhere I can get background-sidebar.html so I can just put it in the right folder?

**Comment by thesnaglebeast** [comment]
fixed with ctrl+f5.
