### ISSUE TITLE
4.0.0-beta3 Configuration Settings

### ISSUE THREAD

**Issue by Peter360** [foundryvtt/pf2e#3886]
Not sure if this is the correct place to report this

Clicking the button does not open the dialog.

foundry.js:711 
 Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[Detected 1 package: settings-extender]
    at SchemaField._validateType (commons.js:3636:15)
    at SchemaField.validate (commons.js:3363:37)
    at Setting.validate (commons.js:5016:35)
    at new DataModel (commons.js:4793:26)
    at new Document (commons.js:5332:3)
    at new BaseSetting (commons.js:9342:3)
    at new ClientDocumentMixin (foundry.js:12999:5)
    at new Setting (foundry.js:21220:1)
    at ClientSettings.get (foundry.js:2732:19)
    at ExtendedSettingsConfig._prepareCategoryData (foundry.js:71086:31)
    at ExtendedSettingsConfig.getData (foundry.js:59170:23)
    at ExtendedSettingsConfig.getData (settings-extender.js:397:22)
    at ExtendedSettingsConfig._render (foundry.js:5014:29)
    at ExtendedSettingsConfig._render (foundry.js:5739:17)
    at ExtendedSettingsConfig._render (foundry.js:59239:18)
onError	@	foundry.js:711
🎁call_wrapped	@	libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper	@	listeners.js:137
🎁Hooks.onError#0	@	libWrapper-wrapper.js:187
(anonymous)	@	foundry.js:4975
Promise.catch (async)		
render	@	foundry.js:4973
_onSettingsButton	@	foundry.js:75814
dispatch	@	jquery.min.js:2
y.handle	@	jquery.min.js:2

**Comment by stwlam** [comment]
That is a module error (settings extender and/or whatever is using it).
