### ISSUE TITLE
Import Error - 

### ISSUE THREAD

**Issue by PeterJMitchell71** [foundryvtt/pf2e#6193]
Foundry v10.291
Pathfinder 2 system v4.7.1
Pathmuncher v0.1.0

When importing a character, the process fails with the following error message:-
`pathmuncher | DEBUG > Pathmuncher options {pathbuilderId: 108289, addMoney: true, addFeats: true, addSpells: true, addEquipment: true, …}
logger.js:39 pathmuncher | DEBUG > Pathmuncher Source {name: 'Unknown Adventurer', class: 'Swashbuckler', level: 1, ancestry: 'Fetchling', heritage: 'Resolute Fetchling', …}
logger.js:41 pathmuncher | DEBUG > Starting Equipment Rename
logger.js:41 pathmuncher | DEBUG > Finished Equipment Rename
logger.js:41 pathmuncher | DEBUG > Starting Special Rename
logger.js:41 pathmuncher | DEBUG > Finished Special Rename
logger.js:41 pathmuncher | DEBUG > Starting Feat Rename
logger.js:41 pathmuncher | DEBUG > Finished Feat Rename
logger.js:41 pathmuncher | DEBUG > Checking for compendium documents for Not set (deity) in pf2e.deities
logger.js:41 pathmuncher | DEBUG > Checking for compendium documents for Charlatan (background) in pf2e.backgrounds
logger.js:39 pathmuncher | DEBUG > Generating grantItem rule lookups for Charlatan... {document: {…}}
logger.js:39 pathmuncher | DEBUG > addGrantedItems for Charlatan {_id: 'Uw5pWTaHfUFQNLdd', img: 'systems/pf2e/icons/default-icons/background.svg', name: 'Charlatan', system: {…}, type: 'background', …}
logger.js:39 pathmuncher | DEBUG > Checking granted item Charlatan, with key: 3d2il {img: 'systems/pf2e/icons/features/feats/feats.webp', level: 1, name: 'Charming Liar', uuid: 'Compendium.pf2e.feats-srd.B6HbYsLBWb1RR6Fx'}
logger.js:41 pathmuncher | DEBUG > Adding granted item flags to Charming Liar (parent Charlatan)
logger.js:41 pathmuncher | DEBUG > Checking for compendium documents for Swashbuckler (class) in pf2e.classes
logger.js:39 pathmuncher | DEBUG > Generating grantItem rule lookups for Swashbuckler... {document: {…}}
logger.js:39 pathmuncher | DEBUG > addGrantedItems for Swashbuckler {_id: 'k4Uc0nomh1MkBTJo', img: 'systems/pf2e/icons/classes/swashbuckler.webp', name: 'Swashbuckler', system: {…}, type: 'class', …}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: 12j4u {img: 'systems/pf2e/icons/features/classes/evasion.webp', level: 7, name: 'Evasion', uuid: 'Compendium.pf2e.classfeatures.MV6XIuAgN9uSA0Da'}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: 2v2xl {img: 'systems/pf2e/icons/features/classes/panache.webp', level: 1, name: 'Panache', uuid: 'Compendium.pf2e.classfeatures.LzYi0OuOoypNb6jd'}
logger.js:41 pathmuncher | DEBUG > Adding granted item flags to Panache (parent Swashbuckler)
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: 2z1nf {img: 'systems/pf2e/icons/features/classes/precise-strike.webp', level: 1, name: 'Precise Strike', uuid: 'Compendium.pf2e.classfeatures.RQH6vigvhmiYKKjg'}
logger.js:41 pathmuncher | DEBUG > Adding granted item flags to Precise Strike (parent Swashbuckler)
logger.js:39 pathmuncher | DEBUG > addGrantedRules for Precise Strike {_id: 'weTxE0dMoLwL86J5', img: 'systems/pf2e/icons/features/classes/precise-strike.webp', name: 'Precise Strike', system: {…}, type: 'feat', …}
logger.js:39 pathmuncher | DEBUG > Generating grantItem rule lookups for Precise Strike... {document: {…}}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: 41jmp {img: 'systems/pf2e/icons/features/classes/confident-finisher.webp', level: 1, name: 'Confident Finisher', uuid: 'Compendium.pf2e.classfeatures.pyo0vmxUFIFX2GNl'}
logger.js:41 pathmuncher | DEBUG > Adding granted item flags to Confident Finisher (parent Swashbuckler)
logger.js:39 pathmuncher | DEBUG > addGrantedRules for Confident Finisher {_id: 'IPp3liCFYI2Tm1Jx', img: 'systems/pf2e/icons/features/classes/confident-finisher.webp', name: 'Confident Finisher', system: {…}, type: 'feat', …}
logger.js:39 pathmuncher | DEBUG > Generating grantItem rule lookups for Confident Finisher... {document: {…}}
logger.js:41 pathmuncher | DEBUG > Checking Confident Finisher rule key: GrantItem
logger.js:39 pathmuncher | DEBUG > UUID for Confident Finisher: "Compendium.pf2e.actionspf2e.K878asDgf1EF0B9S" {_id: 'IPp3liCFYI2Tm1Jx', img: 'systems/pf2e/icons/features/classes/confident-finisher.webp', name: 'Confident Finisher', system: {…}, type: 'feat', …} {key: 'GrantItem', uuid: 'Compendium.pf2e.actionspf2e.K878asDgf1EF0B9S'} undefined
logger.js:39 pathmuncher | DEBUG > Found rule feature Confident Finisher for Confident Finisher for {key: 'GrantItem', uuid: 'Compendium.pf2e.actionspf2e.K878asDgf1EF0B9S'}
logger.js:41 pathmuncher | DEBUG > Adding granted item flags to Confident Finisher (parent Confident Finisher)
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: 4sxx4 {img: 'systems/pf2e/icons/features/classes/weapon-specialization.webp', level: 7, name: 'Weapon Specialization', uuid: 'Compendium.pf2e.classfeatures.9EqIasqfI8YIM3Pt'}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: 7g9e4 {img: 'systems/pf2e/icons/features/classes/vivacious-speed.webp', level: 3, name: 'Vivacious Speed', uuid: 'Compendium.pf2e.classfeatures.8BOFeRE7ZfJ02N0O'}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: 9bzuj {img: 'systems/pf2e/icons/features/classes/eternal-confidence.webp', level: 19, name: 'Eternal Confidence', uuid: 'Compendium.pf2e.classfeatures.ypfT3iybew6ZSIUl'}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: begqu {img: 'systems/pf2e/icons/features/classes/resolve.webp', level: 17, name: 'Resolve', uuid: 'Compendium.pf2e.classfeatures.JQAujUXjczVnYDEI'}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: biz5f {img: 'systems/pf2e/icons/features/classes/improved-evasion.webp', level: 13, name: 'Improved Evasion', uuid: 'Compendium.pf2e.classfeatures.L5D0NwFXdLiVSnk5'}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: i3ldz {img: 'systems/pf2e/icons/features/classes/greater-weapon-specialization.webp', level: 15, name: 'Greater Weapon Specialization', uuid: 'Compendium.pf2e.classfeatures.Z7HX6TeFsaup7Dx9'}
logger.js:39 pathmuncher | DEBUG > Checking granted item Swashbuckler, with key: jlyi1 {img: 'systems/pf2e/icons/features/classes/choice-feature.webp', level: 1, name: "Swashbuckler's Style", uuid: 'Compendium.pf2e.classfeatures.beW1OqibVQ3fBvRw'}
logger.js:41 pathmuncher | DEBUG > Adding granted item flags to Swashbuckler's Style (parent Swashbuckler)
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Swashbuckler's Style. This might not be an issue, but might indicate feature duplication. {document: {…}, parent: {…}}
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:419
#addGrantedItems @ Pathmuncher.js:721
await in #addGrantedItems (async)
#processGenericCompendiumLookup @ Pathmuncher.js:300
await in #processGenericCompendiumLookup (async)
processCharacter @ Pathmuncher.js:1308
await in processCharacter (async)
_updateObject @ PathmuncherImporter.js:77
await in _updateObject (async)
_onSubmit @ foundry.js:5916
logger.js:39 pathmuncher | DEBUG > addGrantedRules for Swashbuckler's Style {_id: 'hJH8D2lfTNqnhdkx', img: 'systems/pf2e/icons/features/classes/choice-feature.webp', name: "Swashbuckler's Style", system: {…}, type: 'feat', …}
logger.js:39 pathmuncher | DEBUG > Generating grantItem rule lookups for Swashbuckler's Style... {document: {…}}
logger.js:39 pathmuncher | DEBUG > Generating rule for... {document: {…}, rule: {…}}
logger.js:39 pathmuncher | DEBUG > Evaluating choices for Swashbuckler's Style {document: {…}, choiceSet: {…}}
commons.js:6946 Foundry VTT | Created Actor with id [mC256tx2waOErogs]
base-theme-hooks.js:13 pf2e-dorako-ui | baseThemeApplications | renderActorDirectoryPF2e => add .dorako-ui
base-theme-hooks.js:14 {app: ActorDirectoryPF2e}
base-theme-hooks.js:28 pf2e-dorako-ui | baseThemeApplications | renderActorDirectoryPF2e => add .dorako-ui
base-theme-hooks.js:29 {app: ActorDirectoryPF2e}
commons.js:6946 Foundry VTT | Created 8 Item documents in parent Actor [mC256tx2waOErogs]
logger.js:39 pathmuncher | DEBUG > Final temp actor CharacterPF2e {rules: Array(2), conditions: Map(0), auras: Map(0), synthetics: {…}, #valid: true, …}
logger.js:39 pathmuncher | DEBUG > Starting choice evaluation {document: {…}, choiceSet: {…}, item: FeatPF2e, choiceSetRules: ChoiceSetRuleElement, rollOptions: Array(56), …}
logger.js:39 pathmuncher | DEBUG > Evaluating choiceset {adjustName: false, allowedDrops: {…}, choices: Array(5), key: 'ChoiceSet', prompt: 'PF2E.SpecificRule.Swashbuckler.Style.Prompt', …}
logger.js:39 pathmuncher | DEBUG > choiceMatch result undefined
commons.js:6946 Foundry VTT | Deleted Actor with id [mC256tx2waOErogs]
logger.js:39 pathmuncher | DEBUG > Evaluate Choices failed {choiceSet: {…}, tempActor: CharacterPF2e, document: {…}}
logger.js:53 pathmuncher | WARN > Failed to resolve injected uuid {ruleData: {…}, flagName: 'swashbucklersStyle', key: 'item', prop: 'flags.pf2e.rulesSelections.swashbucklersStyle', value: undefined}
log @ logger.js:53
warn @ logger.js:79
#generateGrantItemData @ Pathmuncher.js:533
await in #generateGrantItemData (async)
#addGrantedRules @ Pathmuncher.js:617
#addGrantedItems @ Pathmuncher.js:722
await in #addGrantedItems (async)
#processGenericCompendiumLookup @ Pathmuncher.js:300
await in #processGenericCompendiumLookup (async)
processCharacter @ Pathmuncher.js:1308
await in processCharacter (async)
_updateObject @ PathmuncherImporter.js:77
await in _updateObject (async)
_onSubmit @ foundry.js:5916
logger.js:41 pathmuncher | DEBUG > Checking Swashbuckler's Style rule key: ChoiceSet
logger.js:39 pathmuncher | DEBUG > Evaluating choices for Swashbuckler's Style {document: {…}, choiceSet: {…}}
base-theme-hooks.js:13 pf2e-dorako-ui | baseThemeApplications | renderActorDirectoryPF2e => add .dorako-ui
base-theme-hooks.js:14 {app: ActorDirectoryPF2e}
base-theme-hooks.js:28 pf2e-dorako-ui | baseThemeApplications | renderActorDirectoryPF2e => add .dorako-ui
base-theme-hooks.js:29 {app: ActorDirectoryPF2e}
commons.js:6946 Foundry VTT | Created Actor with id [VMmWnt8LmVhEQaNg]
base-theme-hooks.js:13 pf2e-dorako-ui | baseThemeApplications | renderActorDirectoryPF2e => add .dorako-ui
base-theme-hooks.js:14 {app: ActorDirectoryPF2e}
base-theme-hooks.js:28 pf2e-dorako-ui | baseThemeApplications | renderActorDirectoryPF2e => add .dorako-ui
base-theme-hooks.js:29 {app: ActorDirectoryPF2e}
commons.js:6946 Foundry VTT | Created 8 Item documents in parent Actor [VMmWnt8LmVhEQaNg]
logger.js:39 pathmuncher | DEBUG > Final temp actor CharacterPF2e {rules: Array(2), conditions: Map(0), auras: Map(0), synthetics: {…}, #valid: true, …}
commons.js:6946 Foundry VTT | Deleted Actor with id [VMmWnt8LmVhEQaNg]
foundry.js:5919 TypeError: Cannot add property label, object is not extensible
    at LaxSchemaField._cleanType (main.bundle.js:19:631274)
    at LaxSchemaField.clean (commons.js:3767:19)
    at ChoiceSetRuleElement.cleanData (commons.js:5390:26)
    at ChoiceSetRuleElement._initializeSource (commons.js:5377:31)
    at new DataModel (commons.js:5259:21)
    at new RuleElementPF2e (main.bundle.js:19:271064)
    at new ChoiceSetRuleElement (main.bundle.js:19:297055)
    at #evaluateChoices (Pathmuncher.js:440:1)
    at async #addGrantedRules (Pathmuncher.js:627:1)
    at async #addGrantedItems (Pathmuncher.js:722:1)
    at async #processGenericCompendiumLookup (Pathmuncher.js:300:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:1308:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:77:1)
    at async PathmuncherImporter._onSubmit (foundry.js:5916:7)`

**Comment by PeterJMitchell71** [comment]
The specific error message:-
`foundry.js:5919 TypeError: Cannot add property label, object is not extensible
    at LaxSchemaField._cleanType (main.bundle.js:19:631274)
    at LaxSchemaField.clean (commons.js:3767:19)
    at ChoiceSetRuleElement.cleanData (commons.js:5390:26)
    at ChoiceSetRuleElement._initializeSource (commons.js:5377:31)
    at new DataModel (commons.js:5259:21)
    at new RuleElementPF2e (main.bundle.js:19:271064)
    at new ChoiceSetRuleElement (main.bundle.js:19:297055)
    at #evaluateChoices (Pathmuncher.js:440:1)
    at async #addGrantedRules (Pathmuncher.js:627:1)
    at async #addGrantedItems (Pathmuncher.js:722:1)
    at async #processGenericCompendiumLookup (Pathmuncher.js:300:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:1308:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:77:1)
    at async PathmuncherImporter._onSubmit (foundry.js:5916:7)`

**Comment by PeterJMitchell71** [comment]
Posted on werong Github...apologies
