### ISSUE TITLE
Can't open a custom heritage sheet after creation

### ISSUE THREAD

**Issue by OberusPing** [foundryvtt/pf2e#6251]
With no modules active, I am getting the following error when trying to create a custom heritage item:

foundry.js:747 TypeError: An error occurred while rendering HeritageSheetPF2e 122. Cannot read properties of undefined (reading 'filter')
[Detected 1 package: system:pf2e]
at main.bundle.js:1:847964
at HeritageSheetPF2e.getData (main.bundle.js:1:848357)
at async HeritageSheetPF2e.getData (main.bundle.js:1:772685)
at async HeritageSheetPF2e._render (foundry.js:5108:18)
at async HeritageSheetPF2e._render (foundry.js:5822:5)
at async exports.maintainTagifyFocusInRender (main.bundle.js:19:423903)
at async HeritageSheetPF2e._render (main.bundle.js:1:859143)

**Comment by OberusPing** [comment]
With no modules active, I am getting the following error when trying to create a custom heritage item:

foundry.js:747 TypeError: An error occurred while rendering HeritageSheetPF2e 122. Cannot read properties of undefined (reading 'filter')
[Detected 1 package: system:pf2e]
    at main.bundle.js:1:847964
    at HeritageSheetPF2e.getData (main.bundle.js:1:848357)
    at async HeritageSheetPF2e.getData (main.bundle.js:1:772685)
    at async HeritageSheetPF2e._render (foundry.js:5108:18)
    at async HeritageSheetPF2e._render (foundry.js:5822:5)
    at async exports.maintainTagifyFocusInRender (main.bundle.js:19:423903)
    at async HeritageSheetPF2e._render (main.bundle.js:1:859143)
