### ISSUE TITLE
[BUG] Cannot close token config window

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#7954]
PF2e 4.12.0, foundry 10.291, no modules active but Find the Culprit:

-open a token config window (double right click)
-click the x to close
-get error:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'schema')
    at TokenDocument._onUpdateTokenActor (foundry.js:22441:34)
    at TokenDocument._onUpdate (pf2e.mjs:35:335630)
    at TokenConfigPF2e._previewChanges (foundry.js:71120:17)
    at TokenConfigPF2e._resetPreview (foundry.js:71130:10)
    at TokenConfigPF2e.close (foundry.js:71052:32)
    at Object.onclick (foundry.js:5332:29)
    at HTMLAnchorElement.<anonymous> (foundry.js:5239:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```
hitting the Update Token button still works properly.

**Comment by stwlam** [comment]
not able to reproduce: do you have any additional details that would help narrow this?

**Comment by esheyw** [comment]
... No, and now I can't repro it either? Even with my full module load 🤔  I thought it might have been because orhaned token, but it doesn't seem to be that either. I made a new world to test after seeing this, didn't happen there, went back to the world I found it in, doesn't happen there anymore either. So I guess close as non-repro and I'll just assume my game is haunted.
