### ISSUE TITLE
Actor sheets with exploration activities do not load

### ISSUE THREAD

**Issue by Taurahh** [foundryvtt/pf2e#8594]
Attempting to open a sheet with an exploration activity has the following error:

```
undry.js:753 TypeError: An error occurred while rendering CharacterSheetPF2e 116. Cannot read properties of undefined (reading 'includes')
    at #prepareActions (pf2e.mjs:18:169752)
    at CharacterSheetPF2e.getData (pf2e.mjs:18:146762)
    at async CharacterSheetPF2e._render (foundry.js:5785:18)
    at async CharacterSheetPF2e._render (foundry.js:6503:5)
    at async maintainTagifyFocusInRender (pf2e.mjs:6:246485)
    at async CharacterSheetPF2e._render (pf2e.mjs:16:107691)
    at async CharacterSheetPF2e._render (pf2e.mjs:18:101481)
onError @ foundry.js:753
(anonymous) @ foundry.js:5744
Promise.catch (async)
render @ foundry.js:5742
render @ foundry.js:7082
_onClickLeft2 @ foundry.js:56033
callback @ foundry.js:31547
#handleClickLeft2 @ foundry.js:31751
#handleMouseDown @ foundry.js:31718
notifyListeners @ earcut.js:128
notifyTarget @ earcut.js:128
propagate @ earcut.js:128
dispatchEvent @ earcut.js:128
mapPointerDown @ earcut.js:128
mapEvent @ earcut.js:128
onPointerDown @ earcut.js:128
```

Attempting to add an exploration activity to a sheet has the following error, which then prevents the sheet from being reopened:

```
peError: An error occurred while rendering CharacterSheetPF2e 118. Cannot read properties of undefined (reading 'includes')
    at #prepareActions (pf2e.mjs:18:169752)
    at CharacterSheetPF2e.getData (pf2e.mjs:18:146762)
    at async CharacterSheetPF2e._render (foundry.js:5785:18)
    at async CharacterSheetPF2e._render (foundry.js:6503:5)
    at async maintainTagifyFocusInRender (pf2e.mjs:6:246485)
    at async CharacterSheetPF2e._render (pf2e.mjs:16:107691)
    at async CharacterSheetPF2e._render (pf2e.mjs:18:101481)

```

All modules off. Removing exploration activities from the actor's json and reimporting the actor resolves the issue but no new exploration activities can be added.

**Comment by CarlosFdez** [comment]
This seems like a missing template.json (due to a possibly bad install). Let me know if it persists after a reinstallation.

**Comment by HibaniPaws** [comment]
> This seems like a old template.json (due to a possibly bad install). Let me know if it persists after a reinstallation of the pf2e system.

Reinstalling solved the problem for me.

**Comment by Taurahh** [comment]
Reinstalling the PF2e system resolved the problem. Closing the issue. Thanks!
